name: transformers
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - python=3.9.16
  - conda-forge::transformers
  - conda-forge::tensorflow
  - conda-forge::pytorch
  - conda-forge::accelerate